sudo: required

services:
  - docker

# It is not really needed, other than for showing correct language tag in Travis CI build log.
language: cpp

before_install:
  - docker run -d --name ci -v $(pwd):/home/travis/build/$TRAVIS_REPO_SLUG ubuntu:bionic tail -f /dev/null
  - docker ps

install:
  - docker exec -t ci bash -c " apt-get update;
    apt-get install -y build-essential qt5-default python"

script:
  - docker exec -t ci bash -c "c++ --version"
  - docker exec -t ci bash -c "cd /home/travis/build/$TRAVIS_REPO_SLUG && mkdir -p build && cd build"
  - docker exec -t ci bash -c "cd /home/travis/build/$TRAVIS_REPO_SLUG/build && qmake \"CONFIG+=release\" ../qtest_suite.pro -r"
  - docker exec -t ci bash -c "cd /home/travis/build/$TRAVIS_REPO_SLUG/build && make"
  - docker exec -t ci bash -c "cd /home/travis/build/$TRAVIS_REPO_SLUG/build && make -j1 check TESTARGS=\"-silent\""
  - docker exec -t ci bash -c "cd /home/travis/build/$TRAVIS_REPO_SLUG && python external/cpplint-1.3.0/cpplint.py --recursive include tests"
